import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const orderSlice = createApi({
  reducerPath: "orderSlice",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({

    getOrders: builder.query({
      query: (params) => ({
        url: `/shared/dashboard/orders`,
        params,
      }),
    }),

    createOrder: builder.mutation({
      query: (orderData) => ({
        url: '/admin/orders/create',
        method: 'POST',
        body: orderData,
      }),
    }),

  }),
});

// Export hooks generated by the API service
export const {
  useGetOrdersQuery,
  useCreateOrderMutation
} = orderSlice;
