    import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

    // Define your base URL
    const baseUrl = "https://back.biopluskw.com/api/v1";

    // Create the API slice for prescriptions
    export const prescriptionApi = createApi({
    reducerPath: "prescriptionApi",
    baseQuery: fetchBaseQuery({
        baseUrl,
        prepareHeaders: (headers) => {
        // Get the token from localStorage
        const token = localStorage.getItem("token");

        // If a token exists, add it to the headers
        if (token) {
            headers.set("Authorization", `Bearer ${token}`);
        }

        return headers;
        },
    }),

    endpoints: (builder) => ({
        // Get all prescriptions
        getPrescriptions: builder.query({
        query: (params) => ({
            url: '/admin/pharmacy-prescription',
            params: params, // Optional query parameters
        }),
        }),
        
        // Update prescription status
        updatePrescriptionStatus: builder.mutation({
        query: ({ id, status }) => ({
            url: `/admin/pharmacy-prescription/${id}/status`,
            method: "PUT",
            body: { status }, // Send the new status in the request body
        }),
        }),

       // In your prescriptionApi definition
        addPrescriptionToCart: builder.mutation({
        query: ({ id, products }) => ({
            url: `/admin/pharmacy-prescription/${id}/add-to-cart`,
            method: "POST",
            body: { products }, // This matches your required format
        }),
        }),
    }),
    });

    // Export hooks generated by the API service
    export const {
    useGetPrescriptionsQuery,
    useUpdatePrescriptionStatusMutation,
    useAddPrescriptionToCartMutation,
    } = prescriptionApi;