import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const ProductApi = createApi({
  reducerPath: "ProductApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // Debug logging
      console.log('Token from localStorage:', token);
      console.log('Token type:', typeof token);
      console.log('Token length:', token ? token.length : 'null');

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
        console.log('Authorization header set:', `Bearer ${token}`);
      } else {
        console.log('No token found in localStorage');
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({
    getProducts: builder.query({
      query: (params) => ({
        url: '/admin/products',
        params: params, 
      }),
    }),
    
    getProduct: builder.query({
      query: (id) => `/admin/products/${id}`,
    }),
    addProduct: builder.mutation({
      query: (data) => ({
        url: "/admin/products",
        method: "POST",
        body: data,
      }),
    }),
    updateProduct: builder.mutation({
      query: ({ id, data }) => ({
        url: `/admin/products/${id}`,
        method: "PUT",
        body: data,
      }),
    }),
    deleteProduct: builder.mutation({
      query: (id) => ({
        url: `/admin/products/${id}`,
        method: "DELETE",
      }),
    }),
    getBulkUploadTemplate: builder.query({
      query: () => ({
        url: '/admin/product-bulk-upload/template',
        responseHandler: (response) => response.blob(),
      }),
    }),
    exportAllProducts: builder.query({
      query: (pharmacyId) => ({
        url: `/admin/products/export/all?pharmacyId=${pharmacyId}`,
        responseHandler: (response) => response.blob(),
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetProductsQuery,
  useGetProductQuery,
  useUpdateProductMutation,
  useAddProductMutation,
  useDeleteProductMutation,
  useGetBulkUploadTemplateQuery,
  useExportAllProductsQuery
} = ProductApi;

