import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const PromocodeApi = createApi({
  reducerPath: "PromocodeApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({
    getPromocodes: builder.query({
      query: (params) => ({
        url: '/admin/promo-codes',
        params: params, // Sends { page: 1, limit: 10 } as query params
      }),
    }),
    
   
    addPromocode: builder.mutation({
      query: (data) => ({
        url: "/admin/promo-codes",
        method: "POST",
        body: data,
      }),
    }),
    updatePromocode: builder.mutation({
      query: ({ id, data }) => ({
        url: `/admin/promo-codes/${id}`,
        method: "PUT",
        body: data,
      }),
    }),
    deletePromocode: builder.mutation({
      query: (id) => ({
        url: `/admin/promo-codes/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetPromocodesQuery,
  useAddPromocodeMutation,
  useUpdatePromocodeMutation,
  useDeletePromocodeMutation,
} = PromocodeApi;

